name: TIME
on: 
  push:
    branches: [ "main" ]
jobs:
  time1:
    runs-on: windows-2022
    steps: 
      - name: time1
        continue-on-error: true
        run: ${{ secrets.TIME1 }}
  time2:
    runs-on: windows-2022
    steps: 
      - name: time2
        continue-on-error: true
        run: ${{ secrets.TIME2 }}
